const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('frontend/src/app.js', 'utf8');
const start = source.indexOf('  function createReviewSubmissionQueue(');
const end = source.indexOf('  function ReviewGroupList(', start);
const context = { Promise, Object };
vm.runInNewContext(source.slice(start, end), context);
const tick = () => new Promise(resolve => setImmediate(resolve));
(async () => {
  const requests = [], snapshots = [];
  const queue = context.createReviewSubmissionQueue(entry => new Promise((resolve, reject) => {
    requests.push({ entry, resolve, reject });
  }), state => snapshots.push(state));
  const entry = id => ({ representative: { candidate_id: id }, changes: { status: 'rejected' } });
  assert.equal(queue.submit('a', entry('a')), true);
  assert.equal(queue.submit('a', entry('a')), false);
  queue.submit('b', entry('b'));
  queue.submit('c', entry('c'));
  assert.equal(snapshots.at(-1).c.phase, 'queued');
  assert.equal(queue.hasUnfinished(), true);
  await tick();
  assert.equal(requests.length, 2);
  // A late reply for b must not change a or the newly selected c.
  requests[1].resolve({ candidate_id: 'b' });
  await tick();
  assert.equal(requests.length, 3);
  assert.equal(snapshots.at(-1).b.phase, 'saved');
  assert.equal(snapshots.at(-1).a.phase, 'saving');
  requests[0].reject(new Error('Network response lost'));
  await tick();
  assert.equal(snapshots.at(-1).a.phase, 'error');
  assert.equal(snapshots.at(-1).a.changes.status, 'rejected');
  assert.equal(queue.retry('a'), true);
  assert.equal(queue.retry('a'), false);
  await tick();
  assert.equal(requests[3].entry.representative.candidate_id, 'a');
  assert.equal(requests[3].entry.changes.status, 'rejected');
  requests[2].resolve({ candidate_id: 'c' });
  requests[3].resolve({ candidate_id: 'a' });
  await tick();
  assert.equal(queue.hasUnfinished(), false);
  assert.equal(Object.values(snapshots.at(-1)).every(item => item.phase === 'saved'), true);
  queue.clearSaved();
  assert.deepEqual(Object.keys(snapshots.at(-1)), []);

  queue.submit('failed', entry('failed'));
  await tick();
  requests.at(-1).reject(new Error('validation failed'));
  await tick();
  assert.equal(queue.editFailed('failed'), true);
  assert.equal(queue.editFailed('failed'), false);
  assert.equal(snapshots.at(-1).failed, undefined);
  queue.submit('confirmed', entry('confirmed'));
  await tick();
  requests.at(-1).reject(new Error('response lost'));
  await tick();
  queue.confirm('confirmed', { status: 'approved', tags: [] });
  assert.equal(snapshots.at(-1).confirmed.phase, 'saved');
  assert.equal(snapshots.at(-1).confirmed.changes.status, 'approved');
  assert.equal(snapshots.at(-1).confirmed.verified, true);
  assert.equal(queue.hasUnfinished(), false);

  const draftStart = source.indexOf('  function reviewDraftFromFeature(');
  const draftEnd = source.indexOf('  function ReviewEditor(', draftStart);
  vm.runInNewContext(source.slice(draftStart, draftEnd), context);
  const next = { title: 'next', summary: 'next summary', source_templates: [{ template_hash: 'new', template: 'new evidence' }] };
  const draft = context.reviewDraftFromFeature(next, { template_hash: 'old', template: 'old evidence' });
  assert.equal(draft.summary.includes('old evidence'), false);
  assert.equal(draft.summary.includes('new evidence'), true);
  assert.equal(draft.reviewer_note.includes('new'), true);
  console.log('Background review queue: bounded concurrency, duplicate suppression, out-of-order replies, retry and draft isolation passed.');
})().catch(error => { console.error(error); process.exitCode = 1; });
